version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
services:
  app:
    build:
      context: app
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_PATH}:/var/www/html
      - ./app/logs/nginx:/var/log/nginx
      - ./app/.composer:/root/.composer
      - ./app/resolv.conf:/etc/resolv.conf
    depends_on:
      - postgres
    networks:
      backend:
        aliases:
          - php-services.portal.localhost

  postgres:
    image: supabase/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=portal
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - backend